import glob, os, re
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['ps.useafm'] = True
matplotlib.rcParams['pdf.use14corefonts'] = True
matplotlib.rcParams['text.usetex'] = True

dir_path = os.getcwd()
print dir_path
print "Hello"
filenames = glob.glob(dir_path+'\stopping_1deg\\autogenerated_0.text')
print dir_path+'\stopping_1deg\\autogenerated*.text'
print filenames
for file_name in filenames:
  data = open(file_name,'r')
  file_string = data.read() #entire file is one string, each line has \r\n
  line_ends = [m.start() for m in re.finditer('\n',file_string)]
  line_list = []
  line_list.append(file_string[:line_ends[0]])
  for idx in range(len(line_ends)-1):
    line_list.append(file_string[line_ends[idx]+1:line_ends[idx+1]]) #makes a list with each line of list containing each line of text file
  content={'inside_count':[], 'num_particles':[], 'theta':[], 'time':[]}
  for idx in range(1,len(line_list)):
    curr_line = line_list[idx]
    l = [m.start() for m in re.finditer(' ',curr_line)]
    content['inside_count'].append(curr_line[:l[0]]) 
    content['num_particles'].append(curr_line[l[0]+1:l[1]])
    content['theta'].append(curr_line[l[1]+1:l[2]])
    content['time'].append(curr_line[l[2]+1:])
  #Now all the values are in the dictionary, now plot
  #V = [float(content['inside_count'][idx])/float(content['num_particles'][idx]) for idx in range(len(content['inside_count']))]
  V = [float(content['inside_count'][idx]) for idx in range(len(content['inside_count']))]
  th = [float(theta) for theta in content['theta']]
  th_dv_list = []
  dV_dth = []
  for idx in range(len(V)-1):
    if (abs(th[idx+1] - th[idx]) > 0.0 ) and abs(V[idx+1]-V[idx])>0.0 :
      dV_dth.append((V[idx+1]-V[idx])/(th[idx+1]-th[idx]))
      th_dv_list.append((th[idx] + 0.5*(th[idx+1] - th[idx])))
  fig = plt.figure(figsize=(20,6), dpi=80, facecolor='w', edgecolor='k')
  ax = fig.gca()
  ax.plot(th,V, 'r', label=('$V(\\theta)'))
  ax.plot(th_dv_list,dV_dth, 'b', label=('$\\frac{dV}{d\\theta}$'))
  plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.) 
  print file_name
#   plt.show()
  path = 'D:\\documents\\flex-110\flex\output\stopping_1deg\\autogenerated_0_plot.png'
  plt.savefig("test.png")
  plt.close(fig)
 

