name: labliquidvision
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - python=3.9.16
  - ipykernel
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - pip
  - pip:
    - black
    - matplotlib==3.7.1
    - ipykernel==6.19.2
    - numpy==1.23.5
    - flake8
    - scikit-learn
    - tqdm
    - matplotlib-inline
    - pyrealsense2==2.53.1.4623
    - opencv-python
    - chardet
    - dvc
    - dvc[gdrive]
    - pandas
    - pyyaml
    - ur_rtde






